### ISSUE TITLE
Show diff for entire file

### ISSUE THREAD

**Issue by vjpr** [samu/git-diff-details#58]
It took me a while to realize that it would only show the diff when I had the caret placed on some lines that were changed. I thought it wasn't working before this.

Can we make it so that it shows all diffs in the document when toggling?

**Comment by samu** [comment]
Thanks for reporting this. I didn't realize this would be confusing, but i totally understand. 

It would certainly be a cool feature to have the plugin show all the diffs in a document. However, right now i'd like to be a bit conservative about it. I see this plugin more as a tool to take a quick glimpse at a single diff. In my personal workflow, whenever im at the point where i want to commit something, i use the command line or Github Desktop to take a look at _all_ the changes in the file. I simply don't think it's necessary to have this type of feature in this package. There's also quite a lot of change that comes with this feature: the code changes would not be trivial, it changes the workflow of how you work with the package, and i don't want to deal with performance issues (what happens if we have a ton of diffs inside a document?). So for now i'm not going to implement this feature.

**Comment by vjpr** [comment]
Thanks for the reply.

You're right, theres a lot to think about and getting good performance would be tricky.

I use SourceTree at the moment but was looking for something more integrated. Good to know that others are using external git tool too.
